### PR TITLE
[vpj][all] Create a new module for offline components to reduce leakage

### PR DESCRIPTION
**Pull request by nisargthakkar**
## Create a new module for offline components to reduce leakage

Recently, we moved some shared classes into `venice-common` to share common functionality. To do this, we added `hadoop-common` library into `venice-common`. However, this leaks `hadoop-common` into online components too which is not desired. Moved these classes into a `venice-hadoop-common` package

## How was this PR tested?

GHCI

## Does this PR introduce any user-facing changes?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by FelixGV** [comment]
Who needs to depend on this module besides VPJ?

**Review by haoxu07 — APPROVED** [review]
LGTM! Thanks for preparing this!

**Comment by nisargthakkar** [comment]
> Who needs to depend on this module besides VPJ?

We have an ETL module internally that would benefit from this. This class was originally copied from there into OSS. We plan to release in open-source at some point. It is just a matter of allocating some bandwidth for

**Comment by FelixGV** [comment]
> > Who needs to depend on this module besides VPJ?
> We have an ETL module internally that would benefit from this. This class was originally copied from there into OSS. We plan to release in open-source at some point. It is just a matter of allocating some bandwidth for

Creating a new module just for the sake of this proprietary ETL depender does not seem quite right... can ETL depend on all of VPJ instead?

**Pull request merged**
