### PR TITLE
[ask for feedback][not ready to merge][build] Add Codecov integration

### PR DESCRIPTION
**Pull request by adamxchen**
## Summary

Per #343, @sushantmane suggested that we can use cloud-based code coverage tool so we could have the following benefits:
1. No need to download and look at the reports from Github action because Codecov provides a friendly UI for us to see.
2. No need to wait for 10+ minutes to build things on local to reproduce the issue or build the coverage reports.
3. Visualize the coverage trends easily. Right now, we don't have this ability.
4. Be more flexible and relax on [code coverage requirement](https://docs.codecov.com/docs/common-recipe-list).
5. A free Codecov badge can be added to our README 😄 

However, it also has a few downsides which we may not like
1. It only supports [line coverage](https://docs.codecov.com/docs/about-code-coverage). I've asked for branch coverage support but there's [no active support](https://community.codecov.com/t/java-jacoco-branch-coverage-support/4270/3) yet. In fact, most of popular cloud-based code coverage tool, e.g. Code Climate, Coveralls, I've checked so far only support line coverage.
2. Due to (1), if we switch from branch coverage to line coverage, the chance is we may have to do more work to please the god of code coverage because if a new commit has no branches, then the branch coverage is N/A so no requirements here, which is not the case for line coverage.
      a. maybe we don't switch, but use it as a reporting tool however it doesn't make much sense if we don't use line coverage
4. The Codecov also reports [Unexpected Coverage Changes](https://docs.codecov.com/docs/unexpected-coverage-changes), which can be confusing at the first sight when read the coverage report.

## How was this PR tested?

Tried it on my personal repo. See https://github.com/adamxchen/venice/pull/4

Screenshot 2023-04-17 at 5 41 03 PM

Screenshot 2023-04-17 at 5 41 15 PM

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by adamxchen** [comment]
Codecov doesn't show reports for this PR because there's no baseline to compare against so please check my sample PR https://github.com/adamxchen/venice/pull/4 here

**Comment by sixpluszero** [comment]
Regrading the downside you posted about no branch coverage - if there is N/A for branch coverage, I don't see how this leads to "do more work" as you mentioned? Shouldn't it be less work since we don't need to write test to pass the branch coverage?

**Comment by adamxchen** [comment]
> Regrading the downside you posted about no branch coverage - if there is N/A for branch coverage, I don't see how this leads to "do more work" as you mentioned? Shouldn't it be less work since we don't need to write test to pass the branch coverage?

You might read it wrong. I was saying we may need to do more when switch to line coverage

**Comment by adamxchen** [comment]
Let me close this for now. Given codecov doens't support branch coverage yet, if we switch to line coverage now, we will have to do more work to fulfill the code coverage requirement.  Given the current status, I think it's better to wait when we build more solid coverage base first.

**Pull request closed without merging**
