### PR TITLE
[server] Fixed union handling in AAWC

### PR DESCRIPTION
**Pull request by FelixGV**
There was a bug where we assumed unions always used null as the first branch.

Introduced a new SchemaUtils::unwrapOptionalUnion function which replaces several other functions from that class.

Thanks to @sixpluszero for finding that this is the root cause of an issue.

## How was this PR tested?
New existing unit tests.

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by ZacAttack** [comment]
Didn't we do work previously to make sure that null was always the first branch?  I seem to recall an issue awhile back where we had to backfill on this and put guard rails in the controller....

**Comment by sixpluszero** [comment]
> Didn't we do work previously to make sure that null was always the first branch? I seem to recall an issue awhile back where we had to backfill on this and put guard rails in the controller....

This must be very old schema, even though I don't know how to check that. v1-v3 seems invalid to me for the original incident store.

**Review by ZacAttack — APPROVED** [review]
I guess it doesn't hurt to be defensive.  I still seem to recall that null not being first breaks some avro rule.

**Comment by FelixGV** [comment]
> I guess it doesn't hurt to be defensive. I still seem to recall that null not being first breaks some avro rule.

No that is not correct AFAIK.

The rule in Avro is that the type of the default value must correspond to the type of the first branch of the enum. Therefore, both of these are valid:

```
{
  "name": "field1",
  "doc": "Epoch time of when a heartbeat is generated.",
  "type": ["null", "long"],
  "default": null
},
{
  "name": "field2",
  "doc": "Epoch time of when a heartbeat is generated.",
  "type": ["long", "null"],
  "default": 0
}
```

But both of these are invalid:

```
{
  "name": "field1",
  "doc": "Epoch time of when a heartbeat is generated.",
  "type": ["null", "long"],
  "default": 0
},
{
  "name": "field2",
  "doc": "Epoch time of when a heartbeat is generated.",
  "type": ["long", "null"],
  "default": null
}
```

**Pull request merged**
