### PR TITLE
[build] Disable parallel running for unit tests

### PR DESCRIPTION
**Pull request by adamxchen**
## Summary

We introduced the Gradle flag to run unit tests in parallel in #262 and hope it can run tasks faster but turned out for some reasons, Gradle will run `diffCoverage` and `JacocoTestCoverageVerification` together at first, though the first task should depend on the latter one.

We didn't figure out how to make `diffCoverage` depends on the `JacocoTestCoverageVerification` yet so the changes above will cause the  `diffCoverage` fail immediately because the Jacoco coverage reports aren't ready yet - it's still running.

Right now, let's disable it and unblock other PRs (reported by #250 )

## How was this PR tested?

Github CI

### CODE REVIEW

**Review by sixpluszero — APPROVED** [review]

**Comment by sushantmane** [comment]
Can running `JacocoTestCoverageVerification` first with tests and then `diffCoverage` solve this problem?

**Review by FelixGV — DISMISSED** [review]
Thanks Adam!

**Review by sushantmane — APPROVED** [review]
Thanks, Adam! We can experiment later to see if we can run `JacocoTestCoverageVerification` and `diffCoverage` separately.

**Review by sushantmane — APPROVED** [review]
lgtm! Thanks

**Pull request merged**
