### PR TITLE
[vpj] Merge venice-hadoop-common back into VPJ

### PR DESCRIPTION
**Pull request by nisargthakkar**
## Merge `venice-hadoop-common` back into VPJ

`venice-hadoop-common` holds some shared classes that we want to use in our internal ETL. But in OSS, it doesn't serve a purpose other than a shared lib for `venice-push-job`. Move these classes back into `venice-push-job`

## How was this PR tested?

GHCI

## Does this PR introduce any user-facing changes?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Review by FelixGV — APPROVED** [review]
Thanks Nisarg.

**Comment by mynameborat** [comment]
I remember there was another util file `SchemaUtils`. What about that one?

**Comment by mynameborat** [comment]
> I remember there was another util file `SchemaUtils`. What about that one?

Sync'd up offline on this. The `SchemaUtils` will remain in `venice-common`. Thank you, @nisargthakkar

**Comment by nisargthakkar** [comment]
> I remember there was another util file `SchemaUtils`. What about that one?

This one is okay to live in `venice-common` since VPJ, DVC and Servers share this

**Pull request merged**
