### PR TITLE
[server] Added config for fast-avro field limit per method

### PR DESCRIPTION
**Pull request by FelixGV**
New config: fast.avro.field.limit.per.method (default 100)

### CODE REVIEW

**Comment by gaojieliu** [comment]
Are you planning to commit this change to the hot-fix branch: `0.4.19`? 
Also we may need this change in client as well, which can be done later.

**Comment by nisargthakkar** [comment]
> Are you planning to commit this change to the hot-fix branch: `0.4.19`? Also we may need this change in client as well, which can be done later.

We need it in the `main` branch too, right? If yes, then we should merge this in main branch, cherry pick it to a branch forked from the hotfix branch, and raise another PR for the hotfix branch

**Comment by FelixGV** [comment]
> We need it in the main branch too, right?

Yes, we do...

**Review by nisargthakkar — APPROVED** [review]
I've not followed the discussions about what this will achieve, but the code change LGTM according per the commit message 😅

**Pull request merged**
