### PR TITLE
[docker] Update venice docker image versions in quick start guides

### PR DESCRIPTION
**Pull request by sushantmane**
## [docker] Update venice docker image versions in quick start guides

Resolves #XXX

## How was this PR tested?

Followed guide: https://venicedb.org/docs/quickstart/quickstart-multi-datacenter

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by sushantmane** [comment]
```stdout
sumane-mn1:docker sumane$ docker-compose -f docker-compose-multi-dc-setup.yaml up -d
[+] Running 19/19
 ✔ Network docker_default                             Created                                                                                                                                                                                           0.0s 
 ✔ Container zookeeper.dc-1.venicedb.io               Healthy                                                                                                                                                                                           6.2s 
 ✔ Container zookeeper.dc-parent.venicedb.io          Healthy                                                                                                                                                                                           6.2s 
 ✔ Container zookeeper.dc-0.venicedb.io               Healthy                                                                                                                                                                                           6.2s 
 ✔ Container kafka.dc-0.venicedb.io                   Healthy                                                                                                                                                                                          13.9s 
 ✔ Container kafka.dc-parent.venicedb.io              Healthy                                                                                                                                                                                          13.8s 
 ✔ Container kafka.dc-1.venicedb.io                   Healthy                                                                                                                                                                                          13.9s 
 ✔ Container venice-controller.dc-0.venicedb.io       Healthy                                                                                                                                                                                          24.5s 
 ✔ Container venice-controller.dc-parent.venicedb.io  Started                                                                                                                                                                                          14.0s 
 ✔ Container venice-controller.dc-1.venicedb.io       Healthy                                                                                                                                                                                          24.5s 
 ✔ Container venice-server-1.dc-0.venicedb.io         Started                                                                                                                                                                                          24.8s 
 ✔ Container venice-router.dc-0.venicedb.io           Healthy                                                                                                                                                                                          35.2s 
 ✔ Container venice-router.dc-1.venicedb.io           Healthy                                                                                                                                                                                          35.7s 
 ✔ Container venice-server-2.dc-1.venicedb.io         Started                                                                                                                                                                                          25.2s 
 ✔ Container venice-server-2.dc-0.venicedb.io         Started                                                                                                                                                                                          25.2s 
 ✔ Container venice-server-0.dc-1.venicedb.io         Started                                                                                                                                                                                          25.1s 
 ✔ Container venice-server-0.dc-0.venicedb.io         Started                                                                                                                                                                                          25.1s 
 ✔ Container venice-server-1.dc-1.venicedb.io         Started                                                                                                                                                                                          25.2s 
 ✔ Container venice-client                            Started          
 
 

sumane-mn1:logs sumane$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                    PORTS                    NAMES
a652584d1733   venicedb/venice-client:0.4.263       "/bin/sh -c '/bin/sh…"   48 seconds ago   Up 11 seconds                                      venice-client
aa2964fb0284   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 23 seconds (healthy)                            venice-server-1.dc-0.venicedb.io
8c07806a365b   venicedb/venice-router:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-router.dc-1.venicedb.io
43960b683b73   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-server-2.dc-1.venicedb.io
b456c146738c   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-server-2.dc-0.venicedb.io
1eb10759a965   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-server-0.dc-1.venicedb.io
d604a6927b06   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-server-1.dc-1.venicedb.io
2bd31378667a   venicedb/venice-server:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-server-0.dc-0.venicedb.io
3befa2c9ea6e   venicedb/venice-router:0.4.263       "java -jar /opt/veni…"   48 seconds ago   Up 22 seconds (healthy)                            venice-router.dc-0.venicedb.io
f1fbc55bc2c6   venicedb/venice-controller:0.4.263   "java -jar /opt/veni…"   48 seconds ago   Up 33 seconds (healthy)                            venice-controller.dc-parent.venicedb.io
e3bbf45243e7   venicedb/venice-controller:0.4.263   "java -jar /opt/veni…"   48 seconds ago   Up 33 seconds (healthy)                            venice-controller.dc-0.venicedb.io
d17e1e1b8699   venicedb/venice-controller:0.4.263   "java -jar /opt/veni…"   48 seconds ago   Up 33 seconds (healthy)                            venice-controller.dc-1.venicedb.io
9c0aa17f0a00   venicedb/apache-kafka:3.3.1          "/bin/sh -c 'bash ka…"   48 seconds ago   Up 41 seconds (healthy)                            kafka.dc-0.venicedb.io
eea15d43f74b   venicedb/apache-kafka:3.3.1          "/bin/sh -c 'bash ka…"   48 seconds ago   Up 41 seconds (healthy)                            kafka.dc-parent.venicedb.io
217699402e3e   venicedb/apache-kafka:3.3.1          "/bin/sh -c 'bash ka…"   48 seconds ago   Up 41 seconds (healthy)                            kafka.dc-1.venicedb.io
e851e41ccb22   venicedb/apache-zookeeper:3.9.0      "/bin/sh -c 'java -j…"   48 seconds ago   Up 47 seconds (healthy)   0.0.0.0:2190->2181/tcp   zookeeper.dc-parent.venicedb.io
a560fe3a9820   venicedb/apache-zookeeper:3.9.0      "/bin/sh -c 'java -j…"   48 seconds ago   Up 47 seconds (healthy)   0.0.0.0:2191->2181/tcp   zookeeper.dc-0.venicedb.io
c4cafeb5d15d   venicedb/apache-zookeeper:3.9.0      "/bin/sh -c 'java -j…"   48 seconds ago   Up 47 seconds (healthy)   0.0.0.0:2192->2181/tcp   zookeeper.dc-1.venicedb.io
```

**Review by FelixGV — APPROVED** [review]
Thanks a lot Sushant!!!

**Comment by sushantmane** [comment]
Thanks for the review, @FelixGV!

**Comment by adamxchen** [comment]
We can probably add Github CI to build build at some point so we can automate this.

**Pull request merged**
