### PR TITLE
Bump netty version to 4.1.74.Final

### PR DESCRIPTION
**Pull request by majisourav99**
## Bump netty version to 4.1.74.Final

 Bump netty version to 4.1.74.Final

## How was this PR tested?

GHCI
## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Review by nisargthakkar — APPROVED** [review]

**Comment by nisargthakkar** [comment]
Anyone knows why Github has not been requiring fresh approvals when new commits are pushed?

**Comment by majisourav99** [comment]
Guess unless there is no new diff in the new commit, it wont ask for approval.

From: Nisarg Thakkar ***@***.***>
Date: Thursday, October 26, 2023 at 2:05 PM
To: linkedin/venice ***@***.***>
Cc: Sourav Maji ***@***.***>, Author ***@***.***>
Subject: Re: [linkedin/venice] Bump netty version to 4.1.74.Final (PR #715)

Anyone knows why Github has not been requiring fresh approvals when new commits are pushed?

**Comment by FelixGV** [comment]
> Anyone knows why Github has not been requiring fresh approvals when new commits are pushed?

I changed the branch protection rules to align with @sushantmane's PR #716. Maybe I messed things up...?

**Comment by nisargthakkar** [comment]
I think this has been the case before the change to the rules. I noticed it yesterday too

**Pull request merged**
