### PR TITLE
[build] Split UnitTestsAndCodeCoverage GH-CI job into UnitTestsAndCodeCoverage and AvroCompatibilityTests

### PR DESCRIPTION
**Pull request by sushantmane**
## Split UnitTestsAndCodeCoverage GH-CI job into UnitTestsAndCodeCoverage and AvroCompatibilityTests

Resolves #XXX

## Does this PR introduce any user-facing changes?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by FelixGV** [comment]
Hi Sushant, I think it is a good idea to split off Avro compat tests since they aren't unit tests. The lowered time outs may be cutting it a bit close though, IDK if there is much to gain there, since hangs in our tests aren't that frequent anymore, AFAICT, so terminating hangs quicker may not be frequently useful. Duration-wise, seems like bucket K may be the long poll now? Maybe we added new tests there recently...

**Comment by sushantmane** [comment]
> Hi Sushant, I think it is a good idea to split off Avro compat tests since they aren't unit tests. The lowered time outs may be cutting it a bit close though, IDK if there is much to gain there, since hangs in our tests aren't that frequent anymore, AFAICT, so terminating hangs quicker may not be frequently useful. 

Yeah, reducing timeouts isn't that helpful. I am reverting it. 

>Duration-wise, seems like bucket K may be the long poll now? Maybe we added new tests there recently...
It seems that the time taken for K and Z fluctuates a lot (12-30 mins diff). Not sure why it happens though. 

Thanks.

**Review by FelixGV — APPROVED** [review]
Thanks Sushant!

**Comment by sushantmane** [comment]
Thank you for the review, Felix!

**Pull request merged**
