### PR TITLE
[server][router] Removing unneeded Optional to reduce memory allocation

### PR DESCRIPTION
**Pull request by alex-dubrouski**
## Optimizing memory allocation buy removing unneeded Optional wrapper
- Reduced memory allocation

## How was this PR tested?
No testing needed

## Does this PR introduce any user-facing changes?
- No

### CODE REVIEW

**Review by nisargthakkar — APPROVED** [review]

**Review by gaojieliu — APPROVED** [review]
Not sure whether the change will be blocked by unit test coverage check or not..

**Comment by alex-dubrouski** [comment]
Funny, I tried to optimize for the fast path but JIT showed me middle finger and generated the same code for a benchmark:
```
    if (_attributes != null) {
      return _attributes;
    }
    return _attributes = new DefaultAttributeMap();
//vs
    if (_attributes == null) {
      _attributes = new DefaultAttributeMap();
    }
    return _attributes;
```
the result in both cases is 
```
             0x00007fb8a84d4435: mov    $0x1,%ebp
             0x00007fb8a84d443a: test   %r10d,%r10d
         ╭   0x00007fb8a84d443d: jne    0x00007fb8a84d4480  ;*ifeq {reexecute=0 rethrow=0 return_oop=0}
.........
         ↘   0x00007fb8a84d4480: movabs $0x7fb8bfbf0ae0,%r10
```
:D

**Comment by FelixGV** [comment]
> Funny, I tried to optimize for the fast path but JIT showed me middle finger and generated the same code for a benchmark:
> 
> ```
> 
>     if (_attributes != null) {
> 
>       return _attributes;
> 
>     }
> 
>     return _attributes = new DefaultAttributeMap();
> 
> //vs
> 
>     if (_attributes == null) {
> 
>       _attributes = new DefaultAttributeMap();
> 
>     }
> 
>     return _attributes;
> 
> ```
> 
> the result in both cases is 
> 
> ```
> 
>   1.46%  │↗  0x00007fb27c4d4940: mov    0x50(%rsp),%r10    //get this
> 
>   6.21%  ││  0x00007fb27c4d4945: mov    0xc(%r10),%r11d    //get field
> 
>   0.99%  ││  0x00007fb27c4d4949: test   %r11d,%r11d        //null check
> 
>          ││  0x00007fb27c4d494c: je     0x00007fb27c4d49b9 //if null
> 
> ```
> 
> 
> 
> :D 

The second one looks more readable, IMHO, than the assignment inside the return line. What do you think?

**Review by FelixGV — APPROVED** [review]
Thanks Alex!

**Pull request merged**
