### PR TITLE
[server] Fork hotfix feature branch off Venice release 0.4.52

### PR DESCRIPTION
**Pull request by majisourav99**
## Fork hotfix release branch off 0.4.52 + include VarHandle optimization.

JVM deoptimization causing latency spike.
Cutting a hotfix release Including float array deoptimization using VarHandle from fast-avro version 0.2.150 to help with the latency issues.

## How was this PR tested?

CI build
## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Comment by gaojieliu** [comment]
It is weird that a build.gradle file change could trigger a unit test coverage failure..

**Comment by adamxchen** [comment]
> It is weird that a build.gradle file change could trigger a unit test coverage failure..

I've tried to pull this PR locally and turned out VeniceClientCompatibilityTest failed (likely due to the Avro version change?) so the JUnit reports were not generated and resulted in coverage failure, which is the red herring.

**Comment by nisargthakkar** [comment]
Can you update the PR title to just have why we need the hotfix. We don't need to call out that this is a hotfix feature branch in the commit

**Comment by majisourav99** [comment]
> > It is weird that a build.gradle file change could trigger a unit test coverage failure..
> 
> I've tried to pull this PR locally and turned out VeniceClientCompatibilityTest failed (likely due to the Avro version change?) so the JUnit reports were not generated and resulted in coverage failure, which is the red herring.
> 
> However, I couldn't find this from the log. Maybe that's the side-effect of `--continue` flag? @majisourav99 Can you please try to run the tests locally and fix them?

I tried the test locally, it passes fine.

**Pull request merged**
