### PR TITLE
[vpj] Send pushjob details during post-target pushjob

### PR DESCRIPTION
**Pull request by majisourav99**
##  Send pushjob details during post-target pushjob

The push job details are generated and send through controller for various offline tracking of pushjob health. During post canary colo job, it missed to send out pushjob details to the controller, thus it would appear in pushjob detail store that other colo did not finish the pushjob. This PR fixes that issue.

## How was this PR tested?

Integration test.

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Review by adamxchen — COMMENTED** [review]
Overall looks good to me. Thanks for the fix!
One quick question is would the duplicate PushJobDetails causing issue?
Now, we will send one COMPLETED msg at [line 1173](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1173) and then send another one at [line 1297](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1297).

Can you please double-check its consumption to ensure there's not issue? If there's an issue, we have to delay the first msg.

**Comment by majisourav99** [comment]
> Overall looks good to me. Thanks for the fix! One quick question is would the duplicate PushJobDetails causing issue? Now, we will send one COMPLETED msg at [line 1173](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1173) and then send another one at [line 1297](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1297).
> 
> Can you please double-check its consumption to ensure there's not issue? If there's an issue, we have to delay the first msg.

No, its not duplicate sending, first ones are sent for target colo,. But rest of the colo does not even receive the complete status ever.

**Review by adamxchen — DISMISSED** [review]

**Comment by adamxchen** [comment]
> > Overall looks good to me. Thanks for the fix! One quick question is would the duplicate PushJobDetails causing issue? Now, we will send one COMPLETED msg at [line 1173](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1173) and then send another one at [line 1297](https://github.com/linkedin/venice/blob/5340fbf63f68fe7022ae5812a2f17eaf59f7e1f8/clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java#L1297).
> > Can you please double-check its consumption to ensure there's not issue? If there's an issue, we have to delay the first msg.
> 
> No, its not duplicate sending, first ones are sent for target colo,. But rest of the colo does not even receive the complete status ever.

I was thinking about the overall status. Since now it would have two `COMPLETED` so had the ask. Checked the codes and seems no issue. 

🚢

**Review by adamxchen — APPROVED** [review]
Thank you!

**Pull request merged**
