### PR TITLE
[server] Wrapped InterruptException should not fail ingestion during graceful shutdown

### PR DESCRIPTION
**Pull request by xunyin8**
[server] Wrapped InterruptException should not fail ingestion during graceful shutdown

InterruptedException during graceful shutdown shouldn't mark ingestion as error. This is already handled in StoreIngestionTask's catch block. However, some InterruptedException gets caught earlier and end up wrapped by VeniceException by other components prior to the StoreIngestionTask's catch block. Instead of trying to unwrap InterruptedExceptions case by case we will recursively check in StoreIngestionTask for any exceptions caused by InterruptedException and not mark push as failure during graceful shutdown.

## How was this PR tested?
Added an unit test in StoreIngestionTaskTest just for the scenario described.

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Review by FelixGV — CHANGES_REQUESTED** [review]
The catch block starting at 1472 seems contradictory... if it’s a wrapped interrupt we swallow but for an unwrapped one we report error? I think we should eliminate that catch block and let the recursive check be the single piece of logic for interrupts. Should add the Kafka interrupts as well (that util function takes in a varargs I think so it's easy to add more exception types into it).

**Comment by xunyin8** [comment]
I think they are working together and not contradictory. Note the if statement at 1472 is `if (isRunning())` and when we handle the wrapped interrupt exception we check for `!isRunning()`. Essentially if the server is not shutting down we still want to make sure interrupt exception will fail the ingestion.  Only ignore them if the server is shutting down.

**Comment by FelixGV** [comment]
> I think they are working together and not contradictory. Note the if statement at 1472 is `if (isRunning())` and when we handle the wrapped interrupt exception we check for `!isRunning()`. Essentially if the server is not shutting down we still want to make sure interrupt exception will fail the ingestion. Only ignore them if the server is shutting down.

Ok fine, but even if we want to behave differently based on whether `isRunning` or not, I still think we should combine all of that interrupt-handling code in a single place, and always examine recursively. Otherwise it seems confusing.

Essentially, I would suggest getting rid of the catch block at 1472, and doing the following:

```
} catch (VeniceIngestionTaskKilledException e) {
  // Whatever that one is doing already
} catch (VeniceChecksumException e) {
  // Move that logic out of the catch Throwable clause, since it's not unwrapping anything
} catch (Throwable t) {
  if (ExceptionUtils.recursiveClassEquals(t, InterruptedException.class, org.apache.kafka.common.errors.InterruptException.class) {
    if (isRunning()) {
      // report error, as previously happened
    } else {
      // just log but without reporting, as you are doing in this PR
    }
    // Consider whether to return in both branches or only if not running
    }
    
    // The rest of the existing catch Throwable code
}
```

Please LMK if it makes sense.

**Comment by xunyin8** [comment]
That makes sense, let me make the change.

**Review by FelixGV — APPROVED** [review]
Thanks a lot! Looks much better 👌

**Pull request merged**
