### PR TITLE
[Server] Keep producerStateMaxAgeMs unchanged if time-based clearing of expired DIV state is disabled

### PR DESCRIPTION
**Pull request by sushantmane**
## How was this PR tested?
CI

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

**Review by majisourav99 — COMMENTED** [review]
Can we make a test for this in OSS ?

**Comment by sushantmane** [comment]
> Can we make a test for this in OSS ?

SIT is very convoluted to write UTs.. so would prefer skipping it

**Review by majisourav99 — APPROVED** [review]
Thanks for the quick fix

**Comment by sushantmane** [comment]
Thanks for the review, @majisourav99!

**Pull request merged**
